#!/usr/bin/env ruby

$:.unshift File.expand_path(File.dirname(__FILE__))

DATA_PATH = File.expand_path(File.join(File.dirname(__FILE__), 'data'))
CONFS_PATH = File.expand_path(File.join(File.dirname(__FILE__), 'confs'))

require './lib/backup'
require File.join(CONFS_PATH, $*[0])
